version: "3.8"
services:
    client:
        build: ./client
        container_name: omniflow-client
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /client
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./client/package.json
        profiles:
            - donotstart
    user:
        build: ./user
        container_name: omniflow-user
        depends_on:
            - db-user
        ports:
            - 4000:4000
        env_file:
            - path: ./user/.env.development
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./user
                  target: /user
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./user/package.json
    project:
        build: ./project
        container_name: omniflow-project
        depends_on:
            - db-project
            - redpanda
        ports:
            - 4005:4005
        env_file:
            - path: ./project/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            KAFKA_CLIENT_ID: my-app
            DB_URL: mongodb://root:example@db-project:27017
        develop:
            watch:
                - action: sync
                  path: ./project
                  target: /project
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./project/package.json
    team:
        build: ./team
        container_name: omniflow-team
        depends_on:
            - db-team
            - redpanda
        ports:
            - 4010:4010
        env_file:
            - path: ./team/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            KAFKA_CLIENT_ID: my-app
            DB_URL: mongodb://root:example@db-team:27017
        develop:
            watch:
                - action: sync
                  path: ./team
                  target: /team
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./team/package.json
    api-doc:
        build: ./api-doc
        container_name: omniflow-api-doc
        depends_on:
            - db-api-doc
            - redpanda
        ports:
            - 4015:4015
        env_file:
            - path: ./api-doc/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            DB_URL: postgres://user:pass@db-api-doc:5432/db
        develop:
            watch:
                - action: sync
                  path: ./api-doc
                  target: /api-doc
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./api-doc/package.json
    module:
        build: ./module
        container_name: omniflow-module
        depends_on:
            - db-module
            - redpanda
        ports:
            - 4020:4020
        env_file:
            - path: ./module/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            DB_URL: mongodb://root:example@db-module:27017
        develop:
            watch:
                - action: sync
                  path: ./module
                  target: /module
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./module/package.json
    comunication:
        build: ./comunication
        container_name: omniflow-comunication
        depends_on:
            - db-comunication
        ports:
            - 4025:4025
        env_file:
            - path: ./comunication/.env.development
              required: true
        environment:
            DB_URL: mongodb://root:example@db-comunication:27017
        develop:
            watch:
                - action: sync
                  path: ./comunication
                  target: /comunication
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./comunication/package.json
    db-user:
        build: ./db-user
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db_user:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-project:
        build: ./db-project
        image: mongo
        restart: always
        ports:
            - 27018:27017
        volumes:
            - db_project:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-team:
        build: ./db-team
        image: mongo
        restart: always
        ports:
            - 27019:27017
        volumes:
            - db_team:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-module:
        build: ./db-module
        image: mongo
        restart: always
        ports:
            - 27020:27017
        volumes:
            - db_module:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-comunication:
        build: ./db-comunication
        image: mongo
        restart: always
        ports:
            - 27021:27017
        volumes:
            - db_comunication:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-api-doc:
        build: ./db-api-doc
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - db_api_doc:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
    redpanda:
        image: docker.redpanda.com/vectorized/redpanda:v22.2.2
        container_name: omniflow-redpanda
        command:
            - redpanda start
            - --kafka-addr PLAINTEXT://0.0.0.0:29092
            - --advertise-kafka-addr PLAINTEXT://redpanda:29092
        ports:
            - 29092:29092

volumes:
    db_user:
        name: omni_db_user_data
    db_project:
        name: omni_db_project_data
    db_team:
        name: omni_db_team_data
    db_api_doc:
        name: omni_db_api_doc_data
    db_module:
        name: omni_db_module_data
    db_comunication:
        name: omni_db_comunication_data
