version: "3.8"
services:
    client:
        build: ./client
        container_name: omni-client
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /client
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./client/package.json
        profiles:
            - donotstart
    user:
        build: ./user
        container_name: omni-user
        depends_on:
            - db-user
        ports:
            - 4000:4000
        env_file:
            - path: ./user/.env.development
              required: true
        environment:
            DB_URL: mongodb://root:example@db-user:27017
        develop:
            watch:
                - action: sync
                  path: ./user
                  target: /user
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./user/package.json
    project:
        build: ./project
        container_name: omni-project
        depends_on:
            - db-project
            - redpanda
        ports:
            - 4005:4005
        env_file:
            - path: ./project/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            DB_URL: mongodb://root:example@db-project:27017
        develop:
            watch:
                - action: sync
                  path: ./project
                  target: /project
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./project/package.json
    team:
        build: ./team
        container_name: omni-team
        depends_on:
            - db-team
            - redpanda
        ports:
            - 4010:4010
        env_file:
            - path: ./team/.env.development
              required: true
        environment:
            KAFKA_BROKER: redpanda:29092
            DB_URL: mongodb://root:example@db-team:27017
        develop:
            watch:
                - action: sync
                  path: ./team
                  target: /team
                  ignore:
                      - node_modules/
                      - dist/
                - action: rebuild
                  path: ./team/package.json
    db-user:
        build: ./db-user
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db_user:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-project:
        build: ./db-project
        image: mongo
        restart: always
        ports:
            - 27018:27017
        volumes:
            - db_project:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    db-team:
        build: ./db-team
        image: mongo
        restart: always
        ports:
            - 27019:27017
        volumes:
            - db_team:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    redpanda:
        image: docker.redpanda.com/vectorized/redpanda:v22.2.2
        container_name: redpanda_example_broker
        command:
            - redpanda start
            - --kafka-addr PLAINTEXT://0.0.0.0:29092
            - --advertise-kafka-addr PLAINTEXT://redpanda:29092
        ports:
            - 29092:29092

volumes:
    db_user:
        name: omni_db_user_data
    db_project:
        name: omni_db_project_data
    db_team:
        name: omni_db_team_data
