apiVersion: apps/v1
kind: Deployment
metadata:
    name: communication-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: communication
    template:
        metadata:
            labels:
                app: communication
        spec:
            containers:
                - name: communication
                  image: raazimuhammed/omniflow-communication
                  env:
                      - name: PORT
                        value: "4025"
                      - name: SERVER_NAME
                        value: communication
                      - name: DB_URL
                        value: "mongodb://communication-mongo-service:27017/db"
                      - name: LOGGER_URL
                        value: "http://localhost:3000"
                      - name: KAFKA_CLIENT_ID
                        value: my-app
                      - name: KAFKA_BROKER
                        value: kafka-service:9092
                      - name: CORS_ORIGINS
                        valueFrom:
                            secretKeyRef:
                                name: common-secret
                                key: CORS_ORIGINS
                      - name: ACCESS_TOKEN_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: common-secret
                                key: ACCESS_TOKEN_SECRET

---
apiVersion: v1
kind: Service
metadata:
    name: communication-service
spec:
    selector:
        app: communication
    ports:
        - name: communication
          protocol: TCP
          port: 4025
          targetPort: 4025
