apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-design-db-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-design-db
    template:
        metadata:
            labels:
                app: db-design-db
        spec:
            containers:
                - name: db-design-db
                  image: postgres
                  env:
                      - name: POSTGRES_USER
                        value: user
                      - name: POSTGRES_PASSWORD
                        value: pass
                      - name: POSTGRES_DB
                        value: db

---
apiVersion: v1
kind: Service
metadata:
    name: db-design-db-service
spec:
    selector:
        app: db-design-db
    ports:
        - name: db
          protocol: TCP
          port: 5432
          targetPort: 5432
