apiVersion: apps/v1
kind: Deployment
metadata:
    name: loki-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: loki
    template:
        metadata:
            labels:
                app: loki
        spec:
            containers:
                - name: loki
                  image: grafana/loki

---
apiVersion: v1
kind: Service
metadata:
    name: loki-service
spec:
    selector:
        app: loki
    ports:
        - name: loki
          protocol: TCP
          port: 3100
          targetPort: 3100
