apiVersion: apps/v1
kind: Deployment
metadata:
    name: project-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: project
    template:
        metadata:
            labels:
                app: project
        spec:
            containers:
                - name: project
                  image: raazimuhammed/omniflow-project
                  env:
                      - name: PORT
                        value: "4005"
                      - name: SERVER_NAME
                        value: project
                      - name: CORS_ORIGINS
                        value: http://localhost:3000
                      - name: ACCESS_TOKEN_SECRET
                        value: bug7DB375N
                      - name: DB_URL
                        value: "mongodb://project-mongo-service:27017/db"
                      - name: LOGGER_URL
                        value: "http://localhost:3000"
                      - name: KAFKA_CLIENT_ID
                        value: my-app
                      - name: KAFKA_BROKER
                        value: http://localhost:3000

---
apiVersion: v1
kind: Service
metadata:
    name: project-service
spec:
    selector:
        app: project
    ports:
        - name: project
          protocol: TCP
          port: 4005
          targetPort: 4005
