apiVersion: apps/v1
kind: Deployment
metadata:
    name: team-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: team
    template:
        metadata:
            labels:
                app: team
        spec:
            containers:
                - name: team
                  image: raazimuhammed/omniflow-team
                  env:
                      - name: PORT
                        value: "4010"
                      - name: SERVER_NAME
                        value: team
                      - name: CORS_ORIGINS
                        value: http://localhost:3000
                      - name: CLIENT_URL
                        value: http://localhost:3000
                      - name: DB_URL
                        value: "mongodb://team-mongo-service:27017/db"

---
apiVersion: v1
kind: Service
metadata:
    name: team-service
spec:
    selector:
        app: team
    ports:
        - name: team
          protocol: TCP
          port: 4010
          targetPort: 4010
