apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - name: user
                  image: raazimuhammed/omniflow-user
                  env:
                      - name: PORT
                        value: "4000"
                      - name: SERVER_NAME
                        value: user
                      - name: DB_URL
                        value: "mongodb://user-mongo-service:27017/db"
                      - name: LOGGER_URL
                        value: "mongodb://user-mongo-service:27017/db"
                      - name: KAFKA_CLIENT_ID
                        value: my-app
                      - name: KAFKA_BROKER
                        value: kafka-service:9092
                      - name: CORS_ORIGINS
                        valueFrom:
                            secretKeyRef:
                                name: common-secret
                                key: CORS_ORIGINS
                      - name: ACCESS_TOKEN_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: common-secret
                                key: ACCESS_TOKEN_SECRET
                      - name: SMPT_HOST
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: SMPT_HOST
                      - name: SMPT_PORT
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: SMPT_PORT
                      - name: SMPT_SERVICE
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: SMPT_SERVICE
                      - name: SMPT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: SMPT_PASSWORD
                      - name: SMPT_MAIL
                        valueFrom:
                            secretKeyRef:
                                name: email-secret
                                key: SMPT_MAIL
                      - name: BUCKET_NAME
                        valueFrom:
                            secretKeyRef:
                                name: aws-secret
                                key: BUCKET_NAME
                      - name: RESIZED_IMAGE_BUCKET_NAME
                        valueFrom:
                            secretKeyRef:
                                name: aws-secret
                                key: RESIZED_IMAGE_BUCKET_NAME
                      - name: BUCKET_REGION
                        valueFrom:
                            secretKeyRef:
                                name: aws-secret
                                key: BUCKET_REGION
                      - name: AWS_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: aws-secret
                                key: AWS_ACCESS_KEY
                      - name: AWS_SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: aws-secret
                                key: AWS_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user
    ports:
        - name: user
          protocol: TCP
          port: 4000
          targetPort: 4000
