name: deploy-communication

on:
    pull_request:
        paths:
            - "communication/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd communication && npm install && npm run test
            - run: cd communication && docker build -t raazimuhammed/omniflow-communication .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push raazimuhammed/omniflow-communication
