name: deploy-user

on:
    pull_request:
        paths:
            - "user/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd user && npm install && npm run test
            - run: cd user && docker build -t raazimuhammed/omniflow-user .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push raazimuhammed/omniflow-user
