name: deploy-module

on:
    pull_request:
        paths:
            - "module/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd module && npm install && npm run test
            - run: cd module && docker build -t raazimuhammed/omniflow-module .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push raazimuhammed/omniflow-module
