name: tests-team

on:
    pull_request:
        paths:
            - "team/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd team && npm install && npm run test
