name: tests-communication

on:
    pull_request:
        paths:
            - "communication/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd communication && npm install && npm run test
