name: tests-api-doc

on:
    pull_request:
        paths:
            - "api-doc/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd api-doc && npm install && npm run test
