name: tests-project

on:
    pull_request:
        paths:
            - "project/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd project && npm install && npm run test
