name: tests-db-design

on:
    pull_request:
        paths:
            - "db-design/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd db-design && npm install && npm run test
